# Generated by Django 3.1.2 on 2021-08-30 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, default=0, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
