# Generated by Django 3.1.2 on 2021-08-30 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fb', '0002_auto_20210830_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, default='0', null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
